echo "Hi... This is my new Jenkins File !!!"
echo "====================================="
echo "Printing the Users Information"
echo " "
cat /etc/passwd
echo " "
echo "====================================="
echo " "
echo "Added Git hub hook concept"
echo "End of the Script"
